spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hifs?useUnicode=true&characterEncoding=utf8
      username: root
      password: 159874
      druid:
        initial-size: 5
        max-active: 500   
        max-wait: 10000
        use-unfair-lock: true  
        pool-prepared-statements: false 
  jpa:
    hibernate:
     connection:
      release_mode: after_transaction
     ddl-auto: update
    show-sql: true
