spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hifs?useUnicode=true&characterEncoding=utf8
      username: root
      password: 159874
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
